### ISSUE TITLE
its broke!

### ISSUE THREAD

**Issue by beastOP** [kevin-powell/TheBox#1]
Try launching it in your phone browser as a desktop site. Its broke.

**Comment by kevin-powell** [comment]
Works in Firefox. 
Just like on desktop, only Firefox supports subgrid.

![Screenshot_20200622-122113](https://user-images.githubusercontent.com/25749407/85311274-30c2a700-b483-11ea-9415-b7c58d1ba222.png)

**Comment by beastOP** [comment]
N
